M48
; DRILL file {KiCad 7.0.1} date Sun Apr 16 22:16:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-16T22:16:48+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C0.0945
%
G90
G05
T1
X5.284Y-4.2612
T2
X5.6198Y-3.37
X5.6198Y-3.618
X5.6198Y-3.87
X5.6906Y-3.37
X5.6906Y-3.618
X5.6906Y-3.87
T3
X5.284Y-4.4108
T4
X5.372Y-2.9456
T5
X5.372Y-2.6504
T6
X5.62Y-4.5079
X5.62Y-2.384
T7
X2.0623Y-3.33
X2.0623Y-4.508
X4.067Y-3.33
X4.067Y-4.508
T0
M30
